apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: munyaal.app
  namespace: legacy
spec:
  commonName: '*.munyaal.app'
  dnsNames:
    - munyaal.app
    - '*.munyaal.app'
  issuerRef:
    kind: Issuer
    name: letsencrypt-munyaal-app
  secretName: munyaal-app-lts
