apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-softlinker-app
  namespace: legacy
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: calebmoradev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-softlinker-app
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: dodns-secret
              key: token