apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csd-templates-pvc
  namespace: legacy
spec:
  storageClassName: nfs-rwx-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
