apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: refaccionaria-mono-api
    app.kubernetes.io/component: api
    app.kubernetes.io/version: '02e2872'
    app.kubernetes.io/part-of: refaccionaria
  name: refaccionaria-mono-api
  namespace: legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: refaccionaria-mono-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: refaccionaria-mono-api
        app.kubernetes.io/component: api
        app.kubernetes.io/version: '02e2872'
        app.kubernetes.io/part-of: refaccionaria
    spec:
      containers:
        - image: registry.digitalocean.com/softmora/legacy/backend:02e2872
          name: refaccionaria-mono-api
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              cpu: 140m
              memory: 320Mi
            requests:
              cpu: 100m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: auth-secret
            - secretRef:
                name: aws-s3-secret
            - secretRef:
                name: db-refaccionaria-secret
          env:
            - name: INVOICES_PATH
              value: /app/storage/refaccionaria/
            - name: S3_FOLDER
              value: refaccionaria
          volumeMounts:
            - name: csd-legacy
              mountPath: /app/storage
      volumes:
        - name: csd-legacy
          persistentVolumeClaim:
            claimName: csd-legacy-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: refaccionaria-mono-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: refaccionaria
  name: refaccionaria-mono-api
  namespace: legacy
spec:
  ports:
    - name: 80-3000
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: refaccionaria-mono-api
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: refaccionaria-mono-api
  namespace: legacy
spec:
  ingressClassName: nginx
  rules:
    - host: api-legacy-refaccionaria.softlinker.app
      http:
        paths:
          - backend:
              service:
                name: refaccionaria-mono-api
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api-legacy-refaccionaria.softlinker.app
      secretName: softlinker-app-lts
