import { Route } from '../entities/route.entity';
import { Action } from '../../actions/entities/action.entity';

// @ts-ignore
const routes: Partial<Route>[] = [
    {
        'id': 21,
        'isActive': 1,
        'name': 'Dashboard',
        'fatherID': null,
        'level': 1,
        'url': '/',
        'icon': 'mdi-home',
        'mpath': '22.21.',
    },
    {
        'id': 22,
        'isActive': 1,
        'name': 'Tienda',
        'fatherID': null,
        'level': 2,
        'url': '/tienda',
        'icon': 'mdi-store',
        'mpath': '22.',
    },
    {
        'id': 23,
        'isActive': 1,
        'name': 'Productos',
        'fatherID': 22,
        'level': 2,
        'url': '/tienda/productos',
        'icon': 'mdi-food',
        'mpath': '22.23.',
    },
    {
        'id': 24,
        'isActive': 1,
        'name': 'Clasificacion',
        'fatherID': 22,
        'level': 3,
        'url': '/tienda/clasificaciones',
        'icon': 'mdi-access-point',
        'mpath': '22.23.24.',
    },
    {
        'id': 25,
        'isActive': 1,
        'name': 'Alamacen',
        'fatherID': 22,
        'level': 4,
        'url': '/tienda/almacen',
        'icon': 'mdi-database-settings',
        'mpath': '22.21.25.',
    },
    {
        'id': 26,
        'isActive': 1,
        'name': 'Proveedores',
        'fatherID': 25,
        'level': 1,
        'url': '/tienda/almacen/proveedores',
        'icon': 'mdi-car-side',
        'mpath': '22.25.26.',
    },
    {
        'id': 27,
        'isActive': 1,
        'name': 'Lista de precios',
        'fatherID': 22,
        'level': 1,
        'url': '/tienda/listasprecios',
        'icon': 'mdi-clipboard-list',
        'mpath': '22.27.',
    },
    {
        'id': 28,
        'isActive': 1,
        'name': 'Pedidos',
        'fatherID': 25,
        'level': 2,
        'url': '/tienda/almacen/pedidos',
        'icon': 'mdi-view-list',
        'mpath': '22.21.25.28.',
    },
    {
        'id': 29,
        'isActive': 1,
        'name': 'Academias',
        'fatherID': null,
        'level': 3,
        'url': '/academias',
        'icon': 'mdi-run',
        'mpath': '29.',
    },
    {
        'id': 30,
        'isActive': 1,
        'name': 'Actividades',
        'fatherID': 29,
        'level': 1,
        'url': '/academias/actividades',
        'icon': 'mdi-human-handsup',
        'mpath': '29.30.',
    },
    {
        'id': 31,
        'isActive': 1,
        'name': 'Recargos',
        'fatherID': 74,
        'level': 2,
        'url': '/academias/recargos',
        'icon': 'mdi-chart-line-stacked',
        'mpath': '29.31.',
    },
    {
        'id': 32,
        'isActive': 1,
        'name': 'Actividad-Grupos',
        'fatherID': 29,
        'level': 3,
        'url': '/academias/grupos',
        'icon': 'mdi-account-group',
        'mpath': '29.32.',
    },
    {
        'id': 33,
        'isActive': 1,
        'name': 'Conceptos',
        'fatherID': 29,
        'level': 4,
        'url': '/academias/conceptos',
        'icon': 'mdi-currency-usd',
        'mpath': '29.33.',
    },
    {
        'id': 34,
        'isActive': 1,
        'name': 'Descuentos',
        'fatherID': 74,
        'level': 5,
        'url': '/academias/descuentos',
        'icon': 'mdi-currency-usd-off',
        'mpath': '29.34.',
    },
    {
        'id': 35,
        'isActive': 1,
        'name': 'Inscripciones',
        'fatherID': 29,
        'level': 6,
        'url': '/academias/inscripciones',
        'icon': 'mdi-account-multiple-plus',
        'mpath': '29.35.',
    },
    {
        'id': 36,
        'isActive': 1,
        'name': 'Asignacion de grupos',
        'fatherID': 29,
        'level': 4,
        'url': '/academias/configuracion/grupos',
        'icon': 'mdi-account-group-outline',
        'mpath': '29.36.',
    },
    {
        'id': 37,
        'isActive': 1,
        'name': 'Externos',
        'fatherID': 29,
        'level': 1,
        'url': '/academias/externos',
        'icon': 'mdi-account-supervisor',
        'mpath': '29.37.',
    },
    {
        'id': 38,
        'isActive': 1,
        'name': 'Pagos',
        'fatherID': 29,
        'level': 7,
        'url': '/reportes/academias/porgrupo',
        'icon': 'mdi-home-currency-usd',
        'mpath': '29.38.',
    },
    {
        'id': 39,
        'isActive': 1,
        'name': 'Becas',
        'fatherID': 74,
        'level': 8,
        'url': '/academias/becas',
        'icon': 'mdi-babel',
        'mpath': '29.39.',
    },
    {
        'id': 40,
        'isActive': 1,
        'name': 'Ventas',
        'fatherID': null,
        'level': 4,
        'url': '/cobros',
        'icon': 'mdi-cart',
        'mpath': '40.',
    },
    {
        'id': 41,
        'isActive': 1,
        'name': 'Control Escolar',
        'fatherID': null,
        'level': 5,
        'url': '/colegio',
        'icon': 'mdi-bus-school',
        'mpath': '41.',
    },
    {
        'id': 42,
        'isActive': 1,
        'name': 'Alumnos',
        'fatherID': 41,
        'level': 1,
        'url': '/colegio/alumnos',
        'icon': 'mdi-account-box',
        'mpath': '41.42.',
    },
    {
        'id': 43,
        'isActive': 1,
        'name': 'Ciclos',
        'fatherID': 41,
        'level': 2,
        'url': '/colegio/ctrlescolar/ciclos',
        'icon': 'mdi-calendar',
        'mpath': '41.43.',
    },
    {
        'id': 44,
        'isActive': 1,
        'name': 'asignacion materia',
        'fatherID': 41,
        'level': 3,
        'url': '/colegio/ctrlescolar/asignacionmaterias',
        'icon': 'mdi-set-center',
        'mpath': '41.44.',
    },
    {
        'id': 45,
        'isActive': 1,
        'name': 'Docentes',
        'fatherID': 41,
        'level': 4,
        'url': '/colegio/ctrlescolar/docentes',
        'icon': 'mdi-bookmark-multiple',
        'mpath': '41.45.',
    },
    {
        'id': 46,
        'isActive': 1,
        'name': 'Planes de estudio',
        'fatherID': 41,
        'level': 6,
        'url': '/colegio/ctrlescolar/planes',
        'icon': 'mdi-library-books',
        'mpath': '41.46.',
    },
    {
        'id': 47,
        'isActive': 1,
        'name': 'Materias',
        'fatherID': 41,
        'level': 7,
        'url': '/colegio/ctrlescolar/materias',
        'icon': 'mdi-book-open-variant',
        'mpath': '41.47.',
    },
    {
        'id': 48,
        'isActive': 1,
        'name': 'Grados',
        'fatherID': 41,
        'level': 9,
        'url': '/colegio/ctrlescolar/grados',
        'icon': 'mdi-elevation-rise',
        'mpath': '41.48.',
    },
    {
        'id': 49,
        'isActive': 1,
        'name': 'Niveles',
        'fatherID': 41,
        'level': 8,
        'url': '/colegio/ctrlescolar/niveles',
        'icon': 'mdi-call-made',
        'mpath': '41.49.',
    },
    {
        'id': 50,
        'isActive': 1,
        'name': 'Modalidad',
        'fatherID': 41,
        'level': 10,
        'url': '/colegio/ctrlescolar/modalidades',
        'icon': 'mdi-library-books',
        'mpath': '41.50.',
    },
    {
        'id': 51,
        'isActive': 1,
        'name': 'Extras',
        'fatherID': 41,
        'level': 11,
        'url': '/',
        'icon': 'mdi-settings-outline',
        'mpath': '41.51.',
    },
    {
        'id': 52,
        'isActive': 1,
        'name': 'Bajas',
        'fatherID': 51,
        'level': 1,
        'url': '/colegio/alumnos/inscripcion/ImportarBajaAlumno',
        'icon': 'mdi-arrow-down',
        'mpath': '41.51.52.',
    },
    {
        'id': 53,
        'isActive': 1,
        'name': 'Importas Inscripcion',
        'fatherID': 51,
        'level': 2,
        'url': '/colegio/alumnos/inscripcion/importarInscripcion',
        'icon': 'mdi-database-import',
        'mpath': '41.51.53.',
    },
    {
        'id': 54,
        'isActive': 1,
        'name': 'Inscripcion Masiva',
        'fatherID': 51,
        'level': 3,
        'url': '/colegio/InscripcionesMasivas',
        'icon': 'mdi-database-refresh',
        'mpath': '41.51.54.',
    },
    {
        'id': 55,
        'isActive': 1,
        'name': 'Importar',
        'fatherID': 51,
        'level': 4,
        'url': '/colegio/importar',
        'icon': 'mdi-import',
        'mpath': '41.51.55.',
    },
    {
        'id': 56,
        'isActive': 1,
        'name': 'Reportes',
        'fatherID': null,
        'level': 6,
        'url': '/reportes',
        'icon': 'mdi-file-excel',
        'mpath': '56.',
    },
    {
        'id': 57,
        'isActive': 1,
        'name': 'Familias',
        'fatherID': null,
        'level': 8,
        'url': '/familias',
        'icon': 'mdi-account-details',
        'mpath': '57.',
    },
    {
        'id': 58,
        'isActive': 1,
        'name': 'Configuracion',
        'fatherID': null,
        'level': 9,
        'url': '',
        'icon': 'mdi-cog-outline',
        'mpath': '58.',
    },
    {
        'id': 59,
        'isActive': 1,
        'name': 'Accesos',
        'fatherID': 58,
        'level': 1,
        'url': '',
        'icon': 'mdi-server-security',
        'mpath': '58.59.',
    },
    {
        'id': 60,
        'isActive': 1,
        'name': 'Usuarios',
        'fatherID': 59,
        'level': 1,
        'url': '/usuarios',
        'icon': 'mdi-account',
        'mpath': '58.59.60.',
    },
    {
        'id': 61,
        'isActive': 1,
        'name': 'Routes',
        'fatherID': 59,
        'level': 2,
        'url': '/rutas',
        'icon': 'mdi-google-street-view',
        'mpath': '58.59.61.',
    },
    {
        'id': 62,
        'isActive': 1,
        'name': 'Roles',
        'fatherID': 59,
        'level': 3,
        'url': '/roles',
        'icon': 'mdi-typewriter',
        'mpath': '58.59.62.',
    },
    {
        'id': 63,
        'isActive': 1,
        'name': 'Extras',
        'fatherID': 29,
        'level': 14,
        'url': '',
        'icon': 'mdi-settings-outline',
        'mpath': '29.63.',
    },
    {
        'id': 64,
        'isActive': 1,
        'name': 'Grupos',
        'fatherID': 41,
        'level': 2,
        'url': '/colegio/ctrlescolar/grupos',
        'icon': 'mdi-account-group',
        'mpath': '41.64.',
    },
    {
        'id': 65,
        'isActive': 1,
        'name': 'Factura',
        'fatherID': 58,
        'level': 2,
        'url': '',
        'icon': 'mdi-file-pdf',
        'mpath': '58.65.',
    },
    {
        'id': 66,
        'isActive': 1,
        'name': 'Empresas',
        'fatherID': 65,
        'level': 1,
        'url': '/empresa',
        'icon': 'mdi-office-building',
        'mpath': '58.66.',
    },
    {
        'id': 67,
        'isActive': 1,
        'name': 'Finanzas',
        'fatherID': 58,
        'level': 3,
        'url': '',
        'icon': 'mdi-finance',
        'mpath': '58.67.',
    },
    {
        'id': 68,
        'isActive': 1,
        'name': 'Bancos',
        'fatherID': 67,
        'level': 1,
        'url': '/bancos',
        'icon': 'mdi-bank',
        'mpath': '58.67.68.',
    },
    {
        'id': 69,
        'isActive': 1,
        'name': 'Forma de pagos',
        'fatherID': 67,
        'level': 2,
        'url': '/paymentmethods',
        'icon': 'mdi-cash-register',
        'mpath': '58.67.69.',
    },
    {
        'id': 70,
        'isActive': 1,
        'name': 'Control de Activos',
        'fatherID': null,
        'level': 5,
        'url': '',
        'icon': 'mdi-package-variant',
        'mpath': '70.',
    },
    {
        'id': 71,
        'isActive': 1,
        'name': 'Mobiliario y equipo',
        'fatherID': 70,
        'level': 1,
        'url': '/control-activos/mobiliario-equipo',
        'icon': 'mdi-view-list',
        'mpath': '70.71.',
    },
    {
        'id': 72,
        'isActive': 1,
        'name': 'Asignaciones',
        'fatherID': 70,
        'level': 2,
        'url': '/control-activos/asignaciones',
        'icon': 'mdi-format-list-checks',
        'mpath': '70.72.',
    },
    {
        'id': 73,
        'isActive': 1,
        'name': 'Ubicaciones',
        'fatherID': 70,
        'level': 1,
        'url': '/control-activos/ubicaciones',
        'icon': 'mdi-map-marker-path',
        'mpath': '70.73.',
    },
    {
        'id': 74,
        'isActive': 1,
        'name': 'Herramientas',
        'fatherID': null,
        'level': 7,
        'url': '',
        'icon': 'mdi-tools',
        'mpath': '74.',
    },
    {
        'id': 75,
        'isActive': 1,
        'name': 'Facturas',
        'fatherID': 74,
        'level': 1,
        'url': '/facturas/tienda',
        'icon': 'mdi-file-document-outline',
        'mpath': '74.75.',
    },
    {
        'id': 76,
        'isActive': 1,
        'name': 'Cargos',
        'fatherID': 74,
        'level': 1,
        'url': '/system/cargosextra',
        'icon': 'mdi-square-inc-cash',
        'mpath': '74.76.',
    },
    {
        'id': 77,
        'isActive': 1,
        'name': 'Punto de venta',
        'fatherID': null,
        'level': 5,
        'url': '/ventas',
        'icon': 'mdi-cash-register',
        'mpath': '77.',
    },
    {
        'id': 78,
        'isActive': 1,
        'name': 'Prueba',
        'fatherID': null,
        'level': 1,
        'url': '/pruebas',
        'icon': 'mdi-access-point',
        'mpath': '78.',
    },
    {
        'id': 79,
        'isActive': 1,
        'name': 'Plan de Pagos',
        'fatherID': 41,
        'level': 4,
        'url': '/colegio/ctrlescolar/planes-pago-colegio',
        'icon': 'mdi-account-cash',
        'mpath': '41.79.',
    },
    {
        'id': 80,
        'isActive': 1,
        'name': 'Reporte Ventas',
        'fatherID': 56,
        'level': 2,
        'url': '/reportes/tienda/ventas',
        'icon': 'mdi-microsoft-excel',
        'mpath': '56.80.',
    },
    {
        'id': 81,
        'isActive': 1,
        'name': 'Reportes',
        'fatherID': 56,
        'level': 1,
        'url': '/reportes',
        'icon': 'mdi-file-excel-outline',
        'mpath': '56.81.',
    },
    {
        'id': 82,
        'isActive': 1,
        'name': 'Settings',
        'fatherID': null,
        'level': 1,
        'url': '/settings',
        'icon': 'mdi-cog',
        'mpath': '82.',
    },
    {
        'id': 83,
        'isActive': 1,
        'name': 'Folios',
        'fatherID': null,
        'level': 4,
        'url': '/folios',
        'icon': 'mdi-beaker-plus-outline',
        'mpath': '58.83.',
    },
    {
        'id': 84,
        'isActive': 1,
        'name': 'Sucursales',
        'fatherID': 58,
        'level': 1,
        'url': '/campus',
        'icon': 'mdi-office-building',
        'mpath': '58.84.',
    },
    {
        'id': 85,
        'isActive': 1,
        'name': 'Empresa',
        'fatherID': 58,
        'level': 1,
        'url': '/settings',
        'icon': 'mdi-office-building',
        'mpath': '58.85.',
    },
    {
        'id': 86,
        'isActive': 1,
        'name': 'Importar Datos',
        'fatherID': 58,
        'level': 1,
        'url': '/importar',
        'icon': 'mdi-upload-multiple',
        'mpath': '58.86.',
    },
    {
        'id': 87,
        'isActive': 1,
        'name': 'Alumnos Planes',
        'fatherID': 41,
        'level': 2,
        'url': '/colegio/alumnos/planestudios/conceptos/',
        'icon': 'mdi-attachment',
        'mpath': '41.87.',
    },
    {
        'id': 88,
        'isActive': 1,
        'name': 'Transactions',
        'fatherID': 22,
        'level': 5,
        'url': '/mini-store/transactions',
        'icon': 'mdi-briefcase',
        'mpath': '22.88.',
    },
    {
        'id': 89,
        'isActive': 1,
        'name': 'Finanzas',
        'fatherID': null,
        'level': 3,
        'url': '/mini-store/transactions',
        'icon': 'mdi-finance',
        'mpath': '89.',
    },
    {
        'id': 90,
        'isActive': 1,
        'name': 'Gastos e Ingresos',
        'fatherID': 67,
        'level': 1,
        'url': '/mini-store/transactions',
        'icon': 'mdi-cash-usd',
        'mpath': '58.67.90.',
    },
    {
        'id': 91,
        'isActive': 1,
        'name': 'Gastos e Ingresos',
        'fatherID': 89,
        'level': 1,
        'url': '/mini-store/transactions',
        'icon': 'mdi-cash-usd',
        'mpath': '89.91.',
    },
];
export default routes;