import { MigrationInterface, QueryRunner } from 'typeorm';

export class inscriptionrelation1575311940899 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<any> {
   //  await queryRunner.query('ALTER TABLE `assignment_inscription` DROP FOREIGN KEY `FK_e30334e2ce6f36d36a30375eebc`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_1f7b5021d0b463ee36cc4f91089`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_2152e25097fda253aeaa0ee052f`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_2bd8812e74f2cd403daaf5c40bb`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_3824dd4c580c977607f9e80f058`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_50523f498a736535282f2c0688f`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_58140416443f2e4fd5535e80b31`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_6357ee5428f4bbe4eec13b38496`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_68a88d9a43c0efb6373bfabd7d0`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_700ef1478455373625d9f82cc12`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_77d429bab1f3b1e633e6278705a`', undefined);
   //  await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_c04fe869cbb7e9a8b90aca9a93c`', undefined);
   // // await queryRunner.query('DROP INDEX `FK_2bb7102d7bce7bc902d333e6754` ON `tie_venta_pagos`', undefined);
    // await queryRunner.query('DROP INDEX `FK_732d382445b2c549b6293d564f5` ON `grupos`', undefined);
   // await queryRunner.query('DROP INDEX `FK_d8e745eb38e887e75ae3cf1256b` ON `grupos`', undefined);
    // await queryRunner.query('DROP INDEX `FK_f8f8c33f32a9acb5b7dd28b735d` ON `alumnos`', undefined);
    await queryRunner.query('ALTER TABLE `assignment_inscription` CHANGE `inscriptionId` `assignmentsInscriptionId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `studentId` `inscripStudentId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `groupId` `inscripGroupId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `gradeId` `inscripGradeId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `levelId` `inscripLevelId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `cycleId` `inscripCycleId`  int NULL ', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `campusId` `inscripCampusId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `agentCreatorId` `inscripAgentCreatorId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `agentEditorId` `inscripAgentEditorId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `classroomId` `inscripClassroomId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `studyPlanVariantId`  `inscripStudyPlanVariantId`  int NULL ', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `studyPlanId` `inscripStudyPlanId`  int NULL', undefined);
    await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `cambio` `cambio` float NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `ac_aconceptos` CHANGE `precio` `precio` float NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` CHANGE `neto_solicitud` `neto_solicitud` float NOT NULL', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` CHANGE `cantidad` `cantidad` decimal(15,2) NOT NULL DEFAULT \'0.000\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_ventas` CHANGE `cambio` `cambio` float NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` CHANGE `cantidad` `cantidad` float NOT NULL', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_pagos` CHANGE `cambio` `cambio` float NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_pagos` CHANGE `cantidad` `cantidad` float NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_facturas` CHANGE `total` `total` float NULL', undefined);
    // await queryRunner.query('ALTER TABLE `ciclos` CHANGE `fecha_inicio` `fecha_inicio` timestamp NOT NULL', undefined);
    // await queryRunner.query('ALTER TABLE `ciclos` CHANGE `fecha_fin` `fecha_fin` timestamp NOT NULL', undefined);
    await queryRunner.query('ALTER TABLE `assignment_inscription` ADD CONSTRAINT `FK_47889f259c7b2875ce66cb6b624` FOREIGN KEY (`assignmentsInscriptionId`) REFERENCES `inscripciones`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_bf5d807b48508e376dd62a462e3` FOREIGN KEY (`inscripStudentId`) REFERENCES `alumnos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_2f9dfb5c109e044c5289700c068` FOREIGN KEY (`inscripGroupId`) REFERENCES `grupos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_59c6802cd5db577827f2e17e584` FOREIGN KEY (`inscripGradeId`) REFERENCES `grados`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_99a311bf7eba393a29ce60970a6` FOREIGN KEY (`inscripLevelId`) REFERENCES `niveles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_12debff7a2c88e646336140a2dc` FOREIGN KEY (`inscripCycleId`) REFERENCES `ciclos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_2cf87c494eeaeb993c8033a97c0` FOREIGN KEY (`inscripCampusId`) REFERENCES `planteles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_a5d919b4e96953042bd4ad3a49f` FOREIGN KEY (`inscripAgentCreatorId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_3f19944f96f6f2251da3f30c31a` FOREIGN KEY (`inscripAgentEditorId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_9b9470f33799bcda9df95465967` FOREIGN KEY (`inscripClassroomId`) REFERENCES `classroom`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_2c3487151ae1a36bd351a9e4317` FOREIGN KEY (`inscripStudyPlanVariantId`) REFERENCES `study_plan_variant`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_b2ebb89093158747f664b639bbb` FOREIGN KEY (`inscripStudyPlanId`) REFERENCES `study_plan`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_b2ebb89093158747f664b639bbb`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_2c3487151ae1a36bd351a9e4317`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_9b9470f33799bcda9df95465967`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_3f19944f96f6f2251da3f30c31a`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_a5d919b4e96953042bd4ad3a49f`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_2cf87c494eeaeb993c8033a97c0`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_12debff7a2c88e646336140a2dc`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_99a311bf7eba393a29ce60970a6`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_59c6802cd5db577827f2e17e584`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_2f9dfb5c109e044c5289700c068`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP FOREIGN KEY `FK_bf5d807b48508e376dd62a462e3`', undefined);
    await queryRunner.query('ALTER TABLE `assignment_inscription` DROP FOREIGN KEY `FK_47889f259c7b2875ce66cb6b624`', undefined);
    await queryRunner.query('ALTER TABLE `ciclos` CHANGE `fecha_fin` `fecha_fin` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP', undefined);
    await queryRunner.query('ALTER TABLE `ciclos` CHANGE `fecha_inicio` `fecha_inicio` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', undefined);
    await queryRunner.query('ALTER TABLE `tie_facturas` CHANGE `total` `total` float(12) NULL', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_pagos` CHANGE `cantidad` `cantidad` float(12) NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_pagos` CHANGE `cambio` `cambio` float(12) NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` CHANGE `cantidad` `cantidad` float(12) NOT NULL', undefined);
    await queryRunner.query('ALTER TABLE `tie_ventas` CHANGE `cambio` `cambio` float(12) NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` CHANGE `cantidad` `cantidad` decimal(15,2) NOT NULL DEFAULT \'0.00\'', undefined);
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` CHANGE `neto_solicitud` `neto_solicitud` float(12) NOT NULL', undefined);
    await queryRunner.query('ALTER TABLE `ac_aconceptos` CHANGE `precio` `precio` float(12) NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `cambio` `cambio` float(12) NOT NULL DEFAULT \'0\'', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripStudyPlanId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripStudyPlanVariantId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripClassroomId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripAgentEditorId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripAgentCreatorId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripCampusId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripCycleId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripLevelId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripGradeId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripGroupId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `inscripStudentId`', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `studyPlanId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `studyPlanVariantId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `classroomId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `agentEditorId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `agentCreatorId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `campusId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `cycleId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `levelId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `gradeId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `groupId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `studentId` int NULL', undefined);
    await queryRunner.query('ALTER TABLE `assignment_inscription` CHANGE `assignmentsInscriptionId` `inscriptionId` int NULL', undefined);
    await queryRunner.query('CREATE INDEX `FK_f8f8c33f32a9acb5b7dd28b735d` ON `alumnos` (`studentCampusId`)', undefined);
    await queryRunner.query('CREATE INDEX `FK_d8e745eb38e887e75ae3cf1256b` ON `grupos` (`groupCycleId`)', undefined);
    await queryRunner.query('CREATE INDEX `FK_732d382445b2c549b6293d564f5` ON `grupos` (`groupGradeId`)', undefined);
    await queryRunner.query('CREATE INDEX `FK_2bb7102d7bce7bc902d333e6754` ON `tie_venta_pagos` (`systemPaymentStatusId`)', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_c04fe869cbb7e9a8b90aca9a93c` FOREIGN KEY (`agentCreatorId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_77d429bab1f3b1e633e6278705a` FOREIGN KEY (`agentEditorId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_700ef1478455373625d9f82cc12` FOREIGN KEY (`studyPlanVariantId`) REFERENCES `study_plan_variant`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_68a88d9a43c0efb6373bfabd7d0` FOREIGN KEY (`gradeId`) REFERENCES `grados`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_6357ee5428f4bbe4eec13b38496` FOREIGN KEY (`campusId`) REFERENCES `planteles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_58140416443f2e4fd5535e80b31` FOREIGN KEY (`cycleId`) REFERENCES `ciclos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_50523f498a736535282f2c0688f` FOREIGN KEY (`levelId`) REFERENCES `niveles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_3824dd4c580c977607f9e80f058` FOREIGN KEY (`studyPlanId`) REFERENCES `study_plan`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_2bd8812e74f2cd403daaf5c40bb` FOREIGN KEY (`studentId`) REFERENCES `alumnos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_2152e25097fda253aeaa0ee052f` FOREIGN KEY (`groupId`) REFERENCES `grupos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `inscripciones` ADD CONSTRAINT `FK_1f7b5021d0b463ee36cc4f91089` FOREIGN KEY (`classroomId`) REFERENCES `classroom`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    await queryRunner.query('ALTER TABLE `assignment_inscription` ADD CONSTRAINT `FK_e30334e2ce6f36d36a30375eebc` FOREIGN KEY (`inscriptionId`) REFERENCES `inscripciones`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
  }

}
