import { MigrationInterface, QueryRunner } from 'typeorm';

export class addMulPaysAcademyCharges1587157138779 implements MigrationInterface {
    name = 'addMulPaysAcademyCharges1587157138779';

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` DROP FOREIGN KEY `FK_4f8d215351cbd2856917f105f8d`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` DROP FOREIGN KEY `FK_57e74a76e028749f5e6bfba84ce`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` DROP FOREIGN KEY `FK_cbded12ba86e574162ffac84adc`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` DROP FOREIGN KEY `FK_5c415253d5e7f7e032510b789af`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` DROP FOREIGN KEY `FK_9e28383774755b2e54d59048cdb`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_0d5770332418cc43cd0ae7710e6`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_0fb9bc8178922ec3d9f7d1ee011`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_4031ba5227eb63df6a0f49b427d`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_595901634daa74c375c806e9aff`', undefined);
        await queryRunner.query('CREATE TABLE `ac_charges_details_extra_charges` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `version` int NOT NULL DEFAULT 0, `uuid` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `quantity` int NOT NULL, `applicationType` enum (\'1\', \'2\') NULL, `operationType` enum (\'sum\', \'subtraction\', \'division\', \'multiplication\') NULL, `typeExtraCharge` enum (\'1\', \'2\', \'3\') NULL, `chargeDetailId` int NULL, `systemExtraChargesId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
        await queryRunner.query('CREATE TABLE `ac_charges_methods_payments` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `version` int NOT NULL DEFAULT 0, `uuid` varchar(36) NOT NULL, `codePaymentMethod` varchar(10) NOT NULL, `quantity` decimal(15,6) NOT NULL DEFAULT 0.000000, `date` date NULL, `account` varchar(255) NULL, `bankId` int NULL, `invoiceMethodPaymentId` int NULL, `academyChargePaymentId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
        await queryRunner.query('CREATE TABLE `ac_charge_payments` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `version` int NOT NULL DEFAULT 0, `uuid` varchar(36) NOT NULL, `folio` varchar(45) NOT NULL DEFAULT \'000000000000000\', `change` decimal(15,6) NULL DEFAULT 0.000000, `quantity` decimal(15,6) NOT NULL DEFAULT 0.000000, `dateCancellation` timestamp NULL, `reasonCancellation` text NULL, `observations` text NULL, `stamping` tinyint(1) NOT NULL DEFAULT 0, `isIVA` tinyint(1) NOT NULL DEFAULT 1, `paymentStatusId` enum (\'1\', \'2\', \'3\', \'4\', \'5\', \'6\') NOT NULL DEFAULT \'1\', `academyChargeId` int NULL, `cashierChargeId` int NULL, `cashierChargeCancellationId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP COLUMN `id_externo`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP COLUMN `is_isr`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP COLUMN `is_ivaretencion`', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` ADD `invoiceType` enum (\'Income\', \'Expenses\') NOT NULL DEFAULT \'Income\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` ADD `academyChargePaymentId` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD `version` int NOT NULL DEFAULT 0', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD `uuid` varchar(36) NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobro_detalle` CHANGE `id_ac_cobro` `id_ac_cobro` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `id_agente_facturador` `id_agente_facturador` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `id_agente_cancelador` `id_agente_cancelador` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `id_ac_cobro` `id_ac_cobro` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP COLUMN `id_estado_pago`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD `id_estado_pago` enum (\'1\', \'2\', \'3\', \'4\', \'5\', \'6\') NOT NULL DEFAULT \'1\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_plantel` `id_plantel` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `ciclo` `ciclo` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_agente` `id_agente` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_agente_cancelacion` `id_agente_cancelacion` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_alumno` `id_alumno` int NULL', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` CHANGE `status` `status` tinyint NOT NULL DEFAULT 0', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` ADD CONSTRAINT `FK_5ddab2718f98370c26267470abe` FOREIGN KEY (`bankId`) REFERENCES `facturacion_bancos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` ADD CONSTRAINT `FK_acae38a373028cb392e7721807d` FOREIGN KEY (`invoiceMethodPaymentId`) REFERENCES `facturacion_formas_pago`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` ADD CONSTRAINT `FK_f8484c14a230e1b4c239899bf6b` FOREIGN KEY (`schoolChargePaymentId`) REFERENCES `school_charge_payments`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` ADD CONSTRAINT `FK_c3b15551744babadb7da93f10b6` FOREIGN KEY (`chargeDetailId`) REFERENCES `school_charge_details`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` ADD CONSTRAINT `FK_0000b3a3c7f7bd0733c3c351776` FOREIGN KEY (`systemExtraChargesId`) REFERENCES `ac_descuentos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_details_extra_charges` ADD CONSTRAINT `FK_c2c5c97d8ae1527fbc999257999` FOREIGN KEY (`chargeDetailId`) REFERENCES `ac_cobro_detalle`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_details_extra_charges` ADD CONSTRAINT `FK_a9c107c3d7cb9002e37af033501` FOREIGN KEY (`systemExtraChargesId`) REFERENCES `ac_descuentos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobro_detalle` ADD CONSTRAINT `FK_90579f13dc437d049dae53e0a99` FOREIGN KEY (`id_ac_cobro`) REFERENCES `ac_cobros`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_methods_payments` ADD CONSTRAINT `FK_4a51cfbc11f3b757b331cd6e212` FOREIGN KEY (`bankId`) REFERENCES `facturacion_bancos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_methods_payments` ADD CONSTRAINT `FK_3423e7772dc40813298bcefe1c6` FOREIGN KEY (`invoiceMethodPaymentId`) REFERENCES `facturacion_formas_pago`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_methods_payments` ADD CONSTRAINT `FK_940bb1ff947ce407ed648b2205f` FOREIGN KEY (`academyChargePaymentId`) REFERENCES `ac_charge_payments`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` ADD CONSTRAINT `FK_6df2f372d2f4f417bce0d0f2d93` FOREIGN KEY (`id_agente_facturador`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` ADD CONSTRAINT `FK_59c3cc6ccd722e1d1ce8469a25d` FOREIGN KEY (`id_agente_cancelador`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` ADD CONSTRAINT `FK_2368cb0eed1761b04a8b861982f` FOREIGN KEY (`academyChargePaymentId`) REFERENCES `ac_charge_payments`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` ADD CONSTRAINT `FK_166bfad0da97fab96282ec02998` FOREIGN KEY (`id_ac_cobro`) REFERENCES `ac_cobros`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charge_payments` ADD CONSTRAINT `FK_cf00e879162f8f43d1ead312653` FOREIGN KEY (`academyChargeId`) REFERENCES `ac_cobros`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charge_payments` ADD CONSTRAINT `FK_f3271ab357b016177f8fa954ef6` FOREIGN KEY (`cashierChargeId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_charge_payments` ADD CONSTRAINT `FK_82b3d2869ff37231a9171db809c` FOREIGN KEY (`cashierChargeCancellationId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD CONSTRAINT `FK_6ffe5e51d3d0f37195d69a9bf9c` FOREIGN KEY (`id_plantel`) REFERENCES `planteles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD CONSTRAINT `FK_4471764a458652d2cd114a68521` FOREIGN KEY (`ciclo`) REFERENCES `ciclos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD CONSTRAINT `FK_28643b9248b8c7f3ab046f396a5` FOREIGN KEY (`id_agente`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD CONSTRAINT `FK_c69c9664908d26561e4650462de` FOREIGN KEY (`id_agente_cancelacion`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD CONSTRAINT `FK_c7e179886ac49dff6a49b572c1f` FOREIGN KEY (`id_alumno`) REFERENCES `alumnos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_9b17916e91c177eef5b5ceae518` FOREIGN KEY (`schoolChargePaymentId`) REFERENCES `school_charge_payments`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_0c052ec2848dfb8a8d4deb89677` FOREIGN KEY (`schoolChargeId`) REFERENCES `school_charges`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_6e6c825b99b3be244a5e53c105f` FOREIGN KEY (`agentBillingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_4e540ea94ad2a651b017899903f` FOREIGN KEY (`agentCancelingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_4e540ea94ad2a651b017899903f`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_6e6c825b99b3be244a5e53c105f`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_0c052ec2848dfb8a8d4deb89677`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_9b17916e91c177eef5b5ceae518`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP FOREIGN KEY `FK_c7e179886ac49dff6a49b572c1f`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP FOREIGN KEY `FK_c69c9664908d26561e4650462de`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP FOREIGN KEY `FK_28643b9248b8c7f3ab046f396a5`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP FOREIGN KEY `FK_4471764a458652d2cd114a68521`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP FOREIGN KEY `FK_6ffe5e51d3d0f37195d69a9bf9c`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charge_payments` DROP FOREIGN KEY `FK_82b3d2869ff37231a9171db809c`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charge_payments` DROP FOREIGN KEY `FK_f3271ab357b016177f8fa954ef6`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charge_payments` DROP FOREIGN KEY `FK_cf00e879162f8f43d1ead312653`', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` DROP FOREIGN KEY `FK_166bfad0da97fab96282ec02998`', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` DROP FOREIGN KEY `FK_2368cb0eed1761b04a8b861982f`', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` DROP FOREIGN KEY `FK_59c3cc6ccd722e1d1ce8469a25d`', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` DROP FOREIGN KEY `FK_6df2f372d2f4f417bce0d0f2d93`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_methods_payments` DROP FOREIGN KEY `FK_940bb1ff947ce407ed648b2205f`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_methods_payments` DROP FOREIGN KEY `FK_3423e7772dc40813298bcefe1c6`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_methods_payments` DROP FOREIGN KEY `FK_4a51cfbc11f3b757b331cd6e212`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobro_detalle` DROP FOREIGN KEY `FK_90579f13dc437d049dae53e0a99`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_details_extra_charges` DROP FOREIGN KEY `FK_a9c107c3d7cb9002e37af033501`', undefined);
        await queryRunner.query('ALTER TABLE `ac_charges_details_extra_charges` DROP FOREIGN KEY `FK_c2c5c97d8ae1527fbc999257999`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` DROP FOREIGN KEY `FK_0000b3a3c7f7bd0733c3c351776`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` DROP FOREIGN KEY `FK_c3b15551744babadb7da93f10b6`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` DROP FOREIGN KEY `FK_f8484c14a230e1b4c239899bf6b`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` DROP FOREIGN KEY `FK_acae38a373028cb392e7721807d`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` DROP FOREIGN KEY `FK_5ddab2718f98370c26267470abe`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` CHANGE `status` `status` tinyint NOT NULL DEFAULT \'1\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_alumno` `id_alumno` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_agente_cancelacion` `id_agente_cancelacion` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_agente` `id_agente` int NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `ciclo` `ciclo` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` CHANGE `id_plantel` `id_plantel` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP COLUMN `id_estado_pago`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD `id_estado_pago` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `id_ac_cobro` `id_ac_cobro` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `id_agente_cancelador` `id_agente_cancelador` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `id_agente_facturador` `id_agente_facturador` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobro_detalle` CHANGE `id_ac_cobro` `id_ac_cobro` int NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP COLUMN `uuid`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` DROP COLUMN `version`', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` DROP COLUMN `academyChargePaymentId`', undefined);
        await queryRunner.query('ALTER TABLE `ac_facturas` DROP COLUMN `invoiceType`', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD `is_ivaretencion` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD `is_isr` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('ALTER TABLE `ac_cobros` ADD `id_externo` int NOT NULL DEFAULT \'0\'', undefined);
        await queryRunner.query('DROP TABLE `ac_charge_payments`', undefined);
        await queryRunner.query('DROP TABLE `ac_charges_methods_payments`', undefined);
        await queryRunner.query('DROP TABLE `ac_charges_details_extra_charges`', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_595901634daa74c375c806e9aff` FOREIGN KEY (`schoolChargeId`) REFERENCES `school_charges`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_4031ba5227eb63df6a0f49b427d` FOREIGN KEY (`agentBillingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_0fb9bc8178922ec3d9f7d1ee011` FOREIGN KEY (`schoolChargePaymentId`) REFERENCES `school_charge_payments`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_0d5770332418cc43cd0ae7710e6` FOREIGN KEY (`agentCancelingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` ADD CONSTRAINT `FK_9e28383774755b2e54d59048cdb` FOREIGN KEY (`chargeDetailId`) REFERENCES `school_charge_details`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_details_extra_charges` ADD CONSTRAINT `FK_5c415253d5e7f7e032510b789af` FOREIGN KEY (`systemExtraChargesId`) REFERENCES `ac_descuentos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` ADD CONSTRAINT `FK_cbded12ba86e574162ffac84adc` FOREIGN KEY (`schoolChargePaymentId`) REFERENCES `school_charge_payments`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` ADD CONSTRAINT `FK_57e74a76e028749f5e6bfba84ce` FOREIGN KEY (`invoiceMethodPaymentId`) REFERENCES `facturacion_formas_pago`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `school_charges_methods_payments` ADD CONSTRAINT `FK_4f8d215351cbd2856917f105f8d` FOREIGN KEY (`bankId`) REFERENCES `facturacion_bancos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    }

}
