import { MigrationInterface, QueryRunner } from 'typeorm';

export class changecreateAtTocreateAt1607438816694 implements MigrationInterface {
  name = 'changecreateAtTocreateAt1607438816694';

  public async up(queryRunner: QueryRunner): Promise<void> {

    await queryRunner.query('ALTER TABLE `familias` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `familias` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `familias` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `familias` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_listaprecios` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_clasificaciones` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `facturacion_claves` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `facturacion_claves` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `facturacion_claves` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `facturacion_claves` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `classroom_permission` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `classroom_permission` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `classroom_permission` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `classroom_permission` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `classroom` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `classroom` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `classroom` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `classroom` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_facturas` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_facturas` CHANGE `uuid` `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ciclos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ciclos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ciclos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ciclos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `facturacion_bancos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `sale_returns` CHANGE `createdDate` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_returns` CHANGE `updatedDate` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_returns` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `sale_return_products` CHANGE `createdDate` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_return_products` CHANGE `updatedDate` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_return_products` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_venta_detalle` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `tie_facturas` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_facturas` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `tie_facturas` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `tie_facturas` CHANGE `uuid` `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `classification` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `classification` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `classification` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `classification` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `location` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `location` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `location` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `location` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `fixed_asset` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `fixed_asset` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `fixed_asset` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `fixed_asset` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `employee` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `employee` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `employee` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `employee` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `responsive_letter` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `responsive_letter` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `responsive_letter` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `responsive_letter` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `matrix_company` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `matrix_company` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `matrix_company` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `matrix_company` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `branch_company` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `branch_company` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `branch_company` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `branch_company` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `job_position` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `job_position` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `job_position` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `job_position` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `departamentos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `departamentos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `departamentos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `departamentos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `usuarios` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `usuarios` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `usuarios` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `usuarios` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `planteles` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `planteles` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `planteles` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `planteles` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `niveles` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `niveles` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `niveles` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `niveles` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `grados` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `grados` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `grados` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `grados` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `grupos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `grupos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `grupos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `grupos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `inscripciones` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_modalidades` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_modalidades` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_modalidades` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_modalidades` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `alumnos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `alumnos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `alumnos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `alumnos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_aconceptos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_academias` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_academias` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_academias` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_academias` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_turnos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_turnos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_turnos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_turnos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_grupos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_grupos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_grupos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_grupos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `estado_pagos` CHANGE `created_at` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `estado_pagos` CHANGE `updated_at` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `estado_pagos` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `estado_pagos` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `company` CHANGE `createdDate` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `company` CHANGE `updatedDate` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `company` CHANGE `version` `version` int NOT NULL DEFAULT 0');

    await queryRunner.query('ALTER TABLE `assignment_subject` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `assignment_subject` ADD `uuid` varchar(36) NOT NULL');

    await queryRunner.query('ALTER TABLE `subject` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `subject` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `modality` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `modality` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `teacher` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `teacher` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `incident_classification` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `incident_classification` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `incident` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `incident` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `study_plan` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `study_plan` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `study_plan_variant` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `study_plan_variant` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `assignment_inscription` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `assignment_inscription` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `assignment` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `assignment` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `route` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `route` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `role` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `role` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `check_in` ADD `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `check_in` ADD `uuid` varchar(36) NOT NULL');
    await queryRunner.query('ALTER TABLE `assignment_subject` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `assignment_subject` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `subject` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `subject` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `modality` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `modality` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `teacher` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `teacher` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `incident_classification` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `incident_classification` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `incident` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `incident` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `study_plan` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `study_plan` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `study_plan_variant` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `study_plan_variant` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `assignment_inscription` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `assignment_inscription` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `assignment` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `assignment` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_returns` CHANGE `version` `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `sale_return_products` CHANGE `version` `version` int NOT NULL DEFAULT 0');
    await queryRunner.query('ALTER TABLE `route` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `route` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `role` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `role` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `check_in` CHANGE `createdAt` `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `check_in` CHANGE `updatedAt` `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE `company` CHANGE `version` `version` int NOT NULL');
    await queryRunner.query('ALTER TABLE `check_in` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `check_in` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `role` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `role` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `route` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `route` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_facturas` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_facturas` ADD `uuid` varchar(100) CHARACTER SET "utf8" COLLATE "utf8_spanish_ci" NOT NULL');
    await queryRunner.query('ALTER TABLE `sale_return_products` CHANGE `version` `version` int NOT NULL');
    await queryRunner.query('ALTER TABLE `sale_returns` CHANGE `version` `version` int NOT NULL');
    await queryRunner.query('ALTER TABLE `ac_facturas` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_facturas` ADD `uuid` varchar(100) CHARACTER SET "utf8" COLLATE "utf8_spanish_ci" NOT NULL');
    await queryRunner.query('ALTER TABLE `assignment` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `assignment` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `assignment_inscription` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `assignment_inscription` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `study_plan_variant` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `study_plan_variant` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `study_plan` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `study_plan` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `incident` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `incident` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `incident_classification` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `incident_classification` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `teacher` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `teacher` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `modality` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `modality` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `subject` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `subject` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `assignment_subject` CHANGE `updatedAt` `updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `assignment_subject` CHANGE `createdAt` `createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `company` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `company` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `estado_pagos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `estado_pagos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `estado_pagos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `estado_pagos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_grupos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_grupos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_grupos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_grupos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_turnos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_turnos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_turnos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_turnos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_academias` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_academias` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_academias` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_academias` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `alumnos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `alumnos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `alumnos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `alumnos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_modalidades` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_modalidades` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_modalidades` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_modalidades` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `inscripciones` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `grupos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `grupos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `grupos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `grupos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `grados` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `grados` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `grados` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `grados` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `niveles` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `niveles` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `niveles` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `niveles` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `planteles` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `planteles` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `planteles` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `planteles` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `usuarios` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `usuarios` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `usuarios` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `usuarios` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `departamentos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `departamentos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `departamentos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `departamentos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `job_position` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `job_position` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `job_position` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `job_position` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `branch_company` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `branch_company` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `branch_company` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `branch_company` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `matrix_company` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `matrix_company` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `matrix_company` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `matrix_company` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `responsive_letter` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `responsive_letter` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `responsive_letter` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `responsive_letter` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `employee` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `employee` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `employee` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `employee` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `fixed_asset` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `fixed_asset` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `fixed_asset` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `fixed_asset` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `location` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `location` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `location` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `location` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `classification` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `classification` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `classification` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `classification` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `check_in` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `check_in` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `role` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `role` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `route` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `route` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_facturas` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_facturas` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_facturas` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `sale_return_products` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `sale_return_products` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `sale_return_products` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `sale_returns` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `sale_returns` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `sale_returns` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ciclos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ciclos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ciclos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ciclos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_facturas` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_facturas` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_facturas` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `assignment` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `assignment` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `assignment_inscription` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `assignment_inscription` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `study_plan_variant` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `study_plan_variant` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `study_plan` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `study_plan` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `classroom` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `classroom` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `classroom` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `classroom` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `incident` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `incident` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `incident_classification` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `incident_classification` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `teacher` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `teacher` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `classroom_permission` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `classroom_permission` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `classroom_permission` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `classroom_permission` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `modality` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `modality` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `subject` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `subject` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `assignment_subject` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `assignment_subject` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `facturacion_claves` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `facturacion_claves` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `facturacion_claves` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `facturacion_claves` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `familias` DROP COLUMN `uuid`');
    await queryRunner.query('ALTER TABLE `familias` DROP COLUMN `version`');
    await queryRunner.query('ALTER TABLE `familias` DROP COLUMN `updatedAt`');
    await queryRunner.query('ALTER TABLE `familias` DROP COLUMN `createdAt`');
    await queryRunner.query('ALTER TABLE `company` ADD `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `company` ADD `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `estado_pagos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `estado_pagos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_inscrip_estados` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_forma_pago` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_recargos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_det_descuentos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_grupos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_grupos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_turnos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_turnos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_academias` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_academias` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_aconceptos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_conceptos_cobro` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_inscrip_conceptos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `alumnos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `alumnos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_modalidades` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_modalidades` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `inscripciones` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `grupos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `grupos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `grados` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `grados` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `niveles` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `niveles` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `planteles` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `planteles` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `usuarios` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `usuarios` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `departamentos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `departamentos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `job_position` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `job_position` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `branch_company` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `branch_company` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `matrix_company` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `matrix_company` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `responsive_letter` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `responsive_letter` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `employee` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `employee` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `fixed_asset_assignment` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `fixed_asset` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `fixed_asset` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `location` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `location` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `classification` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `classification` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_facturas` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_facturas` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` ADD `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_venta_detalle` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `sale_return_products` ADD `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_return_products` ADD `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_returns` ADD `updatedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `sale_returns` ADD `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `facturacion_formas_pago` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_venta_forma_pago` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `facturacion_bancos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ciclos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ciclos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_facturas` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_facturas` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_cobro_detalle` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `ac_tipo_descuento` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `classroom` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `classroom` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `classroom_permission` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `classroom_permission` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `facturacion_claves` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `facturacion_claves` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos_productos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_almacen_pedidos` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` ADD `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_almacen_proveedores` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_clasificaciones` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `tie_listaprecios` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `familias` ADD `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
    await queryRunner.query('ALTER TABLE `familias` ADD `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP');
  }

}
