import {MigrationInterface, QueryRunner} from "typeorm";

export class AddDeletedAt1630681860901 implements MigrationInterface {
    name = 'AddDeletedAt1630681860901'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `familia_infofiscal` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `familias` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_listaprecios` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_clasificaciones` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_products_of_providers` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_almacen_proveedores` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos_productos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_claves` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_productos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `assignment_subject` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `subject` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `modality` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `classroom_permission` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `teacher` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `incident_classification` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `incident` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `classroom` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_tipo_descuento` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `mini_store_details_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_payment_charge` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscrip_concepts_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_charges_methods_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_empresas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_facturas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_charge_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobros` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_detalle` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_charges_details_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_descuentos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_details_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_details` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_payment` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `payment_plan_concept` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `payment_plan` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `study_plan` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `study_plan_variant` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `assignment_inscription` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `assignment` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `periods` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ciclos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charge_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_methods_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_bancos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_venta_forma_pago` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_formas_pago` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `sale_returns` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `sale_return_products` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_venta_detalle` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `mini_store_quotation` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_ventas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_transaction` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `cash_register` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `cash_register_transactions` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_venta_pagos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_facturas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `action` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `route` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `permission` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `role` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `check_in` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `classification` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `location` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `fixed_asset` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `fixed_asset_assignment` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `employee` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `responsive_letter` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `matrix_company` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `branch_company` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `job_position` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `departamentos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `usuarios` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `planteles` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `aut_rvoe` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `niveles` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `grados` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `grupos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `inscripciones` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_modalidades` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `alumnos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscripciones_alumnos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscrip_conceptos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_conceptos_cobro` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_aconceptos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_academias` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_turnos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_grupos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_descuentos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_recargos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_forma_pago` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `oauth_access_tokens` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `folios` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscrip_estados` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `estado_pagos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `company` ADD `deletedAt` timestamp(6) NULL");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `company` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `estado_pagos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscrip_estados` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `folios` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `oauth_access_tokens` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_forma_pago` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_recargos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_descuentos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_grupos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_turnos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_academias` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_aconceptos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_conceptos_cobro` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscrip_conceptos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscripciones_alumnos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `alumnos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_modalidades` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `inscripciones` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `grupos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `grados` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `niveles` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `aut_rvoe` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `planteles` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `usuarios` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `departamentos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `job_position` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `branch_company` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `matrix_company` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `responsive_letter` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `employee` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `fixed_asset_assignment` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `fixed_asset` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `location` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `classification` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `check_in` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `role` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `permission` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `route` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `action` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_facturas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_venta_pagos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `cash_register_transactions` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `cash_register` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_transaction` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_ventas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `mini_store_quotation` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_venta_detalle` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `sale_return_products` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `sale_returns` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_formas_pago` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_venta_forma_pago` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_bancos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_methods_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charge_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ciclos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `periods` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `assignment` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `assignment_inscription` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `study_plan_variant` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `study_plan` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `payment_plan` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `payment_plan_concept` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_payment` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_details` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_details_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_descuentos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_charges_details_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_detalle` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobros` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_charge_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_facturas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_empresas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_charges_methods_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscrip_concepts_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_payment_charge` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `mini_store_details_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_tipo_descuento` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `classroom` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `incident` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `incident_classification` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `teacher` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `classroom_permission` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `modality` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `subject` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `assignment_subject` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_productos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_claves` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos_productos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_almacen_proveedores` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_products_of_providers` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_clasificaciones` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_listaprecios` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `familias` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `familia_infofiscal` DROP COLUMN `deletedAt`");
    }

}
