import {MigrationInterface, QueryRunner} from "typeorm";

export class updateCreditNote1634002820095 implements MigrationInterface {
    name = 'updateCreditNote1634002820095'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DROP INDEX `FK_0c0ad3bf9d8d9b8153c6d1a8e5e` ON `ac_aconceptos`");
        await queryRunner.query("CREATE TABLE `credit_note_academy` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, `folio` varchar(255) NULL, `uuid` varchar(100) NOT NULL, `razon_social` varchar(300) NULL, `rfc` varchar(20) NULL, `total` decimal(15,6) NULL DEFAULT 0.000000, `fecha_cancelacion` timestamp NULL, `motivo_cancelacion` text NULL, `invoiceType` enum ('Income', 'Expenses') NOT NULL DEFAULT 'Expenses', `status` enum ('0', '1', '2', '3', '4') NOT NULL DEFAULT '0', `invoiceBranchOfficeId` int NULL, `agentBillingId` int NULL, `agentCancelingId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `credit_note_school` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, `folio` varchar(255) NULL, `uuid` varchar(100) NOT NULL, `razon_social` varchar(300) NULL, `rfc` varchar(20) NULL, `total` decimal(15,6) NULL DEFAULT 0.000000, `fecha_cancelacion` timestamp NULL, `motivo_cancelacion` text NULL, `invoiceType` enum ('Income', 'Expenses') NOT NULL DEFAULT 'Expenses', `status` enum ('0', '1', '2', '3', '4') NOT NULL DEFAULT '0', `invoiceBranchOfficeId` int NULL, `agentBillingId` int NULL, `agentCancelingId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `credit_note_store` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, `folio` varchar(255) NULL, `uuid` varchar(100) NOT NULL, `razon_social` varchar(300) NULL, `rfc` varchar(20) NULL, `total` decimal(15,6) NULL DEFAULT 0.000000, `fecha_cancelacion` timestamp NULL, `motivo_cancelacion` text NULL, `invoiceType` enum ('Income', 'Expenses') NOT NULL DEFAULT 'Income', `status` enum ('0', '1', '2', '3', '4') NOT NULL DEFAULT '0', `invoiceBranchOfficeId` int NULL, `agentBillingId` int NULL, `agentCancelingId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `tie_products_of_priceslists` (`id` int NOT NULL AUTO_INCREMENT, `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), `deletedAt` timestamp(6) NULL, `version` int NOT NULL DEFAULT '0', `uuid` varchar(36) NOT NULL, `precio` decimal(15,6) NULL DEFAULT '0.000000', `precio_con_iva` decimal(15,6) NOT NULL DEFAULT '0.000000', `iva` tinyint(1) NOT NULL, `productId` int NULL, `priceListId` int NULL, `cycleId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `ac_academias` DROP COLUMN `nombre`");
        await queryRunner.query("ALTER TABLE `ac_academias` DROP COLUMN `escolar`");
        await queryRunner.query("ALTER TABLE `familia_infofiscal` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `familias` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_listaprecios` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_clasificaciones` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_products_of_providers` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_almacen_proveedores` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos_productos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_claves` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_productos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `assignment_subject` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `subject` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `modality` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `classroom_permission` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `teacher` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `incident_classification` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `incident` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `classroom` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_tipo_descuento` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `mini_store_details_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_payment_charge` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscrip_concepts_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_charges_methods_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_empresas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_facturas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_facturas` ADD `creditNoteAcademyId` int NULL");
        await queryRunner.query("ALTER TABLE `ac_charge_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobros` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_detalle` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_charges_details_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_descuentos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_details_extra_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_details` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_payment` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `payment_plan_concept` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `payment_plan` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `study_plan` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `study_plan_variant` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `assignment_inscription` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `assignment` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `periods` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ciclos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` ADD `creditNotesSchoolId` int NULL");
        await queryRunner.query("ALTER TABLE `school_charges` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charge_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `school_charges_methods_payments` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_bancos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_venta_forma_pago` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `facturacion_formas_pago` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `sale_returns` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `sale_return_products` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_venta_detalle` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `mini_store_quotation` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_ventas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_transaction` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `cash_register` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `cash_register_transactions` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_venta_pagos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_facturas` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_facturas` ADD `creditNoteStoreId` int NULL");
        await queryRunner.query("ALTER TABLE `action` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `route` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `permission` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `role` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `check_in` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `classification` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `location` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `fixed_asset` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `fixed_asset_assignment` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `employee` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `responsive_letter` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `matrix_company` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `branch_company` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `job_position` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `departamentos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `usuarios` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `planteles` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `aut_rvoe` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `niveles` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `grados` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `grupos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `inscripciones` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_modalidades` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `alumnos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscripciones_alumnos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscrip_conceptos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_conceptos_cobro` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_aconceptos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_academias` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_academias` ADD `name` varchar(300) NOT NULL");
        await queryRunner.query("ALTER TABLE `ac_academias` ADD `school` tinyint(1) NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `ac_turnos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_grupos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_descuentos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_recargos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_cobro_forma_pago` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `oauth_access_tokens` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `folios` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `ac_inscrip_estados` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `estado_pagos` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `company` ADD `deletedAt` timestamp(6) NULL");
        await queryRunner.query("ALTER TABLE `tie_productos` CHANGE `precio_con_iva` `precio_con_iva` decimal(15,6) NULL DEFAULT '0.000000'");
        await queryRunner.query("ALTER TABLE `credit_note_academy` ADD CONSTRAINT `FK_9716441b94175c0c53e55aa5435` FOREIGN KEY (`invoiceBranchOfficeId`) REFERENCES `planteles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_academy` ADD CONSTRAINT `FK_4082df5c41fd3e51a3ad237887f` FOREIGN KEY (`agentBillingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_academy` ADD CONSTRAINT `FK_b5f594a7879aa155d9788225ef5` FOREIGN KEY (`agentCancelingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `ac_facturas` ADD CONSTRAINT `FK_4c07a86f2e3c6d1358a8b014e93` FOREIGN KEY (`creditNoteAcademyId`) REFERENCES `credit_note_academy`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_school` ADD CONSTRAINT `FK_c6050ef953a7928f246b0b3bdca` FOREIGN KEY (`invoiceBranchOfficeId`) REFERENCES `planteles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_school` ADD CONSTRAINT `FK_1686ca62243141f815939046705` FOREIGN KEY (`agentBillingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_school` ADD CONSTRAINT `FK_7e4447dea8a1b22f3613b498759` FOREIGN KEY (`agentCancelingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` ADD CONSTRAINT `FK_abe18cd72aacd62ed072bef0e78` FOREIGN KEY (`creditNotesSchoolId`) REFERENCES `credit_note_school`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_store` ADD CONSTRAINT `FK_8f2b1ff08e4ebdfde1e26d8899e` FOREIGN KEY (`invoiceBranchOfficeId`) REFERENCES `planteles`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_store` ADD CONSTRAINT `FK_2c58adce737a3e06db62eaaf56f` FOREIGN KEY (`agentBillingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `credit_note_store` ADD CONSTRAINT `FK_eb6f286a7155463cf2a457756db` FOREIGN KEY (`agentCancelingId`) REFERENCES `usuarios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `tie_facturas` ADD CONSTRAINT `FK_c8625c51548604bb996d523af8d` FOREIGN KEY (`creditNoteStoreId`) REFERENCES `credit_note_store`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `tie_products_of_priceslists` ADD CONSTRAINT `FK_182991104132376be50cd174242` FOREIGN KEY (`productId`) REFERENCES `tie_productos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `tie_products_of_priceslists` ADD CONSTRAINT `FK_df0cdc820b15dc7c9e85bd5f963` FOREIGN KEY (`priceListId`) REFERENCES `tie_listaprecios`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `tie_products_of_priceslists` ADD CONSTRAINT `FK_4058a9c5add62f962daed217e0e` FOREIGN KEY (`cycleId`) REFERENCES `ciclos`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `tie_products_of_priceslists` DROP FOREIGN KEY `FK_4058a9c5add62f962daed217e0e`");
        await queryRunner.query("ALTER TABLE `tie_products_of_priceslists` DROP FOREIGN KEY `FK_df0cdc820b15dc7c9e85bd5f963`");
        await queryRunner.query("ALTER TABLE `tie_products_of_priceslists` DROP FOREIGN KEY `FK_182991104132376be50cd174242`");
        await queryRunner.query("ALTER TABLE `tie_facturas` DROP FOREIGN KEY `FK_c8625c51548604bb996d523af8d`");
        await queryRunner.query("ALTER TABLE `credit_note_store` DROP FOREIGN KEY `FK_eb6f286a7155463cf2a457756db`");
        await queryRunner.query("ALTER TABLE `credit_note_store` DROP FOREIGN KEY `FK_2c58adce737a3e06db62eaaf56f`");
        await queryRunner.query("ALTER TABLE `credit_note_store` DROP FOREIGN KEY `FK_8f2b1ff08e4ebdfde1e26d8899e`");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` DROP FOREIGN KEY `FK_abe18cd72aacd62ed072bef0e78`");
        await queryRunner.query("ALTER TABLE `credit_note_school` DROP FOREIGN KEY `FK_7e4447dea8a1b22f3613b498759`");
        await queryRunner.query("ALTER TABLE `credit_note_school` DROP FOREIGN KEY `FK_1686ca62243141f815939046705`");
        await queryRunner.query("ALTER TABLE `credit_note_school` DROP FOREIGN KEY `FK_c6050ef953a7928f246b0b3bdca`");
        await queryRunner.query("ALTER TABLE `ac_facturas` DROP FOREIGN KEY `FK_4c07a86f2e3c6d1358a8b014e93`");
        await queryRunner.query("ALTER TABLE `credit_note_academy` DROP FOREIGN KEY `FK_b5f594a7879aa155d9788225ef5`");
        await queryRunner.query("ALTER TABLE `credit_note_academy` DROP FOREIGN KEY `FK_4082df5c41fd3e51a3ad237887f`");
        await queryRunner.query("ALTER TABLE `credit_note_academy` DROP FOREIGN KEY `FK_9716441b94175c0c53e55aa5435`");
        await queryRunner.query("ALTER TABLE `tie_productos` CHANGE `precio_con_iva` `precio_con_iva` decimal(15,6) NOT NULL DEFAULT '0.000000'");
        await queryRunner.query("ALTER TABLE `company` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `estado_pagos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscrip_estados` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `folios` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `oauth_access_tokens` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_forma_pago` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_recargos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_det_descuentos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_grupos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_turnos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_academias` DROP COLUMN `school`");
        await queryRunner.query("ALTER TABLE `ac_academias` DROP COLUMN `name`");
        await queryRunner.query("ALTER TABLE `ac_academias` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_aconceptos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_conceptos_cobro` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscrip_conceptos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscripciones_alumnos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `alumnos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_modalidades` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `inscripciones` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `grupos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `grados` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `niveles` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `aut_rvoe` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `planteles` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `usuarios` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `departamentos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `job_position` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `branch_company` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `matrix_company` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `responsive_letter` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `employee` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `fixed_asset_assignment` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `fixed_asset` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `location` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `classification` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `check_in` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `role` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `permission` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `route` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `action` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_facturas` DROP COLUMN `creditNoteStoreId`");
        await queryRunner.query("ALTER TABLE `tie_facturas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_venta_pagos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `cash_register_transactions` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `cash_register` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_transaction` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_ventas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `mini_store_quotation` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_venta_detalle` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `sale_return_products` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `sale_returns` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_formas_pago` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_venta_forma_pago` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_bancos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_methods_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charge_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` DROP COLUMN `creditNotesSchoolId`");
        await queryRunner.query("ALTER TABLE `school_charges_invoice` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ciclos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `periods` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `assignment` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `assignment_inscription` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `study_plan_variant` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `study_plan` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `payment_plan` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `payment_plan_concept` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_payment` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_details` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_charges_details_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_descuentos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_charges_details_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobro_detalle` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_cobros` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_charge_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_facturas` DROP COLUMN `creditNoteAcademyId`");
        await queryRunner.query("ALTER TABLE `ac_facturas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_empresas` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_charges_methods_payments` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_inscrip_concepts_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `school_payment_charge` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `mini_store_details_extra_charges` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_tipo_descuento` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `classroom` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `incident` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `incident_classification` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `teacher` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `classroom_permission` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `modality` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `subject` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `assignment_subject` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_productos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `facturacion_claves` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos_productos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_almacen_pedidos` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_almacen_proveedores` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_products_of_providers` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_clasificaciones` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `tie_listaprecios` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `familias` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `familia_infofiscal` DROP COLUMN `deletedAt`");
        await queryRunner.query("ALTER TABLE `ac_academias` ADD `escolar` tinyint(1) NOT NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `ac_academias` ADD `nombre` varchar(300) NOT NULL");
        await queryRunner.query("DROP TABLE `tie_products_of_priceslists`");
        await queryRunner.query("DROP TABLE `credit_note_store`");
        await queryRunner.query("DROP TABLE `credit_note_school`");
        await queryRunner.query("DROP TABLE `credit_note_academy`");
        await queryRunner.query("CREATE INDEX `FK_0c0ad3bf9d8d9b8153c6d1a8e5e` ON `ac_aconceptos` (`id_nivel`)");
    }

}
