import { Action } from '../entities/action.entity';


const actions: Partial<Action>[] = [
    {
        id: 1,
        name: 'Agregar',
        description: 'Permite la creacion de cualquier valor en el modulo selecionado',
        icon: 'M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z',
        isDefault: true,
    },
    {
        id: 2,
        name: 'Visualizar',
        description: 'Permite ver cualquier valor en el modulo selecionado',
        icon: 'M17.65,6.35C16.2,4.9 14.21,4 12,4A8,8 0 0,0 4,12A8,8 0 0,0 12,20C15.73,20 18.84,17.45 19.73,14H17.65C16.83,16.33 14.61,18 12,18A6,6 0 0,1 6,12A6,6 0 0,1 12,6C13.66,6 15.14,6.69 16.22,7.78L13,11H20V4L17.65,6.35Z',
        isDefault: true,
    },
    {
        id: 3,
        name: 'Editar',
        description: 'Permite la actualizacion de cualquier valor en el modulo selecionado',
        icon: 'M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z',
        isDefault: true,
    },
    {
        id: 4,
        name: 'Eliminar',
        description: 'Permite la eliminacion de cualquier valor en el modulo selecionado siempre y cuando se permita por el sistema',
        icon: 'M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z',
        isDefault: true,
    },
    {
        id: 5,
        name: 'INGRESOS POR FECHA',
        description: 'Permite la ver el cuadro de ingresos por fecha',
        icon: '',
        isDefault: false,
    },
    {
        id: 6,
        name: 'VENTAS POR FECHA',
        description: 'Permite la ver el cuadro de ventas por fecha',
        icon: '',
        isDefault: false,
    },
    {
        id: 7,
        name: 'CLIENTES',
        description: 'Permite la ver el cuadro del total de clientes',
        icon: '',
        isDefault: false,
    },
    {
        id: 8,
        name: 'CAJEROS',
        description: 'Permite la ver el cuadro del total de cajeros(@)',
        icon: '',
        isDefault: false,
    },
    {
        id: 9,
        name: 'INGRESOS POR MES DEL AÑO',
        description: 'Permite la ver el cuadro de ingresos por año',
        icon: '',
        isDefault: false,
    },
    {
        id: 10,
        name: 'INGRESOS POR FORMA DE PAGO',
        description: 'Permite la ver el cuadro de ingresos por forma de pago',
        icon: '',
        isDefault: false,
    },
    {
        id: 11,
        name: 'MOVIMIENTOS',
        description: 'Permite la ver los movimientos de trasacciones del sistema',
        icon: '',
        isDefault: false,
    },
    {
        id: 12,
        name: 'VENTAS POR CAJERO',
        description: 'Permite la ver las ventas de cajero',
        icon: '',
        isDefault: false,
    },
    {
        id: 13,
        name: 'INFORMACION DE PRODUCTOS',
        description: 'Permite la ver las ventas de cada productos asi como calculos personalisado',
        icon: '',
        isDefault: false,
    },
    {
        id: 14,
        name: 'INSCRITOS A',
        description: 'Permite la ver la cantidad de inscritos',
        icon: '',
        isDefault: false,
    },
    {
        id: 15,
        name: 'BAJAS A',
        description: 'Permite la ver la cantidad de bajas',
        icon: '',
        isDefault: false,
    },
    {
        id: 16,
        name: 'NO INSCRITOS',
        description: 'Permite la ver la cantidad de no inscriptos en el mes',
        icon: '',
        isDefault: false,
    },
    {
        id: 17,
        name: 'INCLUIDAS',
        description: 'Permite la ver la cantidad de clientes que tienen gratuita la actividad',
        icon: '',
        isDefault: false,
    },
    {
        id: 18,
        name: 'RENDIMIENTO TOTAL A',
        description: 'Permite la ver el porcentaje de pagos',
        icon: '',
        isDefault: false,
    },
    {
        id: 19,
        name: 'G TOTAL DE INS A',
        description: 'Permite la ver el porcentaje de pagos',
        icon: '',
        isDefault: false,
    },
    {
        id: 20,
        name: 'G TOTAL DE INSGRESOS A',
        description: 'Permite la ver el porcentaje de pagos',
        icon: '',
        isDefault: false,
    },
    {
        id: 21,
        name: 'RANGO DE FECHA',
        description: 'Permite ver el formulario de rancho de fechas',
        icon: '',
        isDefault: false,
    },
];

export enum ActionsEnum {
    CREATE = 1,
    READ = 2,
    UPDATE = 3,
    DELETE = 4,
    INGRESOS_POR_FECHA = 5,
    VENTAS_POR_FECHA = 6,
    CLIENTES = 7,
    CAJEROS = 8,
    INGRESOS_POR_MES_DEL_ANO = 9,
    INGRESOS_POR_FORMA_DE_PAGO = 10,
    MOVIMIENTOS = 11,
    VENTAS_POR_CAJERO = 12,
    INFORMACION_DE_PRODUCTOS = 13,
    INSCRITOS_A = 14,
    BAJAS_A = 15,
    NO_INSCRITOS = 16,
    INCLUIDAS = 17,
    RENDIMIENTO_TOTAL_A = 18,
    G_TOTAL_DE_INS_A = 19,
    G_TOTAL_DE_INSGRESOS_A = 20,
    RANGO_DE_FECHA = 21
}

export default actions;