import { Action } from '../entities/action.entity';


const actions: Partial<Action>[] = [
    {
        id: 1,
        name: 'CREATE',
        description: 'Permite la creacion de cualquier valor en el modulo selecionado',
        icon: '',
        isDefault: true,
    },
    {
        id: 2,
        name: 'READ',
        description: 'Permite ver cualquier valor en el modulo selecionado',
        icon: '',
        isDefault: true,
    },
    {
        id: 3,
        name: 'UPDATE',
        description: 'Permite la actualizacion de cualquier valor en el modulo selecionado',
        icon: '',
        isDefault: true,
    },
    {
        id: 4,
        name: 'DELETE',
        description: 'Permite la eliminacion de cualquier valor en el modulo selecionado siempre y cuando se permita por el sistema',
        icon: '',
        isDefault: true,
    },
    {
        id: 5,
        name: 'INGRESOS POR FECHA',
        description: 'Permite la ver el cuadro de ingresos por fecha',
        icon: '',
        isDefault: false,
    },
    {
        id: 6,
        name: 'VENTAS POR FECHA',
        description: 'Permite la ver el cuadro de ventas por fecha',
        icon: '',
        isDefault: false,
    },
    {
        id: 7,
        name: 'CLIENTES',
        description: 'Permite la ver el cuadro del total de clientes',
        icon: '',
        isDefault: false,
    },
    {
        id: 8,
        name: 'CAJEROS',
        description: 'Permite la ver el cuadro del total de cajeros(@)',
        icon: '',
        isDefault: false,
    },
    {
        id: 9,
        name: 'INGRESOS POR MES DEL AÑO',
        description: 'Permite la ver el cuadro de ingresos por año',
        icon: '',
        isDefault: false,
    },
    {
        id: 10,
        name: 'INGRESOS POR FORMA DE PAGO',
        description: 'Permite la ver el cuadro de ingresos por forma de pago',
        icon: '',
        isDefault: false,
    },
    {
        id: 11,
        name: 'MOVIMIENTOS',
        description: 'Permite la ver los movimientos de trasacciones del sistema',
        icon: '',
        isDefault: false,
    },
    {
        id: 12,
        name: 'VENTAS POR CAJERO',
        description: 'Permite la ver las ventas de cajero',
        icon: '',
        isDefault: false,
    },
    {
        id: 13,
        name: 'INFORMACION DE PRODUCTOS',
        description: 'Permite la ver las ventas de cada productos asi como calculos personalisado',
        icon: '',
        isDefault: false,
    },
    {
        id: 14,
        name: 'INSCRITOS A',
        description: 'Permite la ver la cantidad de inscritos',
        icon: '',
        isDefault: false,
    },
    {
        id: 15,
        name: 'BAJAS A',
        description: 'Permite la ver la cantidad de bajas',
        icon: '',
        isDefault: false,
    },
    {
        id: 16,
        name: 'NO INSCRITOS',
        description: 'Permite la ver la cantidad de no inscriptos en el mes',
        icon: '',
        isDefault: false,
    },
    {
        id: 17,
        name: 'INCLUIDAS',
        description: 'Permite la ver la cantidad de clientes que tienen gratuita la actividad',
        icon: '',
        isDefault: false,
    },
    {
        id: 18,
        name: 'RENDIMIENTO TOTAL A',
        description: 'Permite la ver el porcentaje de pagos',
        icon: '',
        isDefault: false,
    },
    {
        id: 19,
        name: 'G TOTAL DE INS A',
        description: 'Permite la ver el porcentaje de pagos',
        icon: '',
        isDefault: false,
    },
    {
        id: 20,
        name: 'G TOTAL DE INSGRESOS A',
        description: 'Permite la ver el porcentaje de pagos',
        icon: '',
        isDefault: false,
    },
];

export enum ActionsEnum {
    CREATE = 1,
    READ = 2,
    UPDATE = 3,
    DELETE = 4,
    INGRESOS_POR_FECHA = 5,
    VENTAS_POR_FECHA = 6,
    'CLIENTES' = 7,
    'CAJEROS' = 8,
    'INGRESOS POR MES DEL AÑO' = 9,
    'INGRESOS POR FORMA DE PAGO' = 10,
    'MOVIMIENTOS' = 11,
    'VENTAS POR CAJERO' = 12,
    'INFORMACION DE PRODUCTOS' = 13,
    'INSCRITOS A' = 14,
    'BAJAS A' = 15,
    'NO INSCRITOS' = 16,
    'INCLUIDAS' = 17,
    'RENDIMIENTO TOTAL A' = 18,
    'G TOTAL DE INS A' = 19,
    'G TOTAL DE INSGRESOS A' = 20,
}

export default actions;